name: Flutter APK Builder

on:
  workflow_dispatch:
    inputs:
      zip_name:
        description: "Nama file ZIP Flutter"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
          channel: stable
          cache: true

      - name: Extract Flutter project
        run: |
          mkdir -p project
          unzip -q "${{ inputs.zip_name }}" -d project

      - name: Find pubspec.yaml
        run: |
          PUBSPEC=$(find project -name pubspec.yaml -type f | head -n 1)
          if [ -z "$PUBSPEC" ]; then
            echo "pubspec.yaml tidak ditemukan!"
            exit 1
          fi

          echo "PUBSPEC=$PUBSPEC" >> "$GITHUB_ENV"
          echo "Project ditemukan: $(dirname "$PUBSPEC")"

      - name: Install dependencies
        run: |
          cd "$(dirname "$PUBSPEC")"
          flutter pub get

      - name: Build APK
        run: |
          cd "$(dirname "$PUBSPEC")"
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-apk
          path: "**/build/app/outputs/flutter-apk/app-release.apk"
